image: python
cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python -V
  - python -m pip install --upgrade pytest pytest-cov
  - python -m pip install -r requirements.txt

tests:
  script:
    - python -m pytest --cov=bearparse tests/
